# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41e25d2df7eec1e1f52d7505955ea0c2acc4d258c9f6ce8b10ece415fdcf8bfd99fa9d58476e882742e58e6b033e89d4cad044fe509ac97ea8dfd84c027f32ca

test:
  secret_key_base: 692fcda3c772a0ecbf531eadd19aec7139213177b075d2db0e4c617a72254826f516fd56de6a45c02edb7e7aa8d3bbe22fab24cd94e70ff4e8ef8d42b6c3e6d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
